ACOUSTID_KEY = "7ZrDDcM8"
ACOUSTID_HOST = "api.acoustid.org"
ACOUSTID_PORT = 443

MUSICBRAINZ_SERVER_HOST = "musicbrainz.org"
MUSICBRAINZ_SERVER_PORT = 443
MUSICBRAINZ_OAUTH_CLIENT_ID = "-M9olldwlVbxktaBVLkeQw"
MUSICBRAINZ_OAUTH_CLIENT_SECRET = "QsFWmePAkoVv_PmX-BY5zA"

CAA_HOST = "coverartarchive.org"
CAA_PORT = 443

VARIOUS_ARTISTS_ID = "89ad4ac3-39f7-470e-963a-56509c546377"
SILENCE_TRACK_TITLE = "[silence]"
DATA_TRACK_TITLE = "[data track]"
